### ISSUE TITLE
Been getting biography: The detailed user info was not returned by instagram a lot lately

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#10]
I don't know what is causing it, but last day or so I've been getting biography: The detailed user info was not returned by instagram.  What does that mean and how do I fix it?  I assume it has to do with restrictions on the API.  Do I just wait it out until the API restriction passes or use a VPN or another computer?

**Comment by OllegK** [comment]
Hi, as I got the a "few details grid" is appearing, but "detailed info grid" is never coming, is it correct? How much followers/following persons this contact has? Sometimes I am collecting the followers/following on an IG account who has 24k+ followers/following, and with default interval it takes several hours to return the detailed info. However anyway it shows progress and in case of temporary restriction from IG, it shows countdown and error message in the red. How does it look for you? Do you have any error message? Try to open the developer tools and check if there are uncaught errors in console?

**Comment by thinkpad4** [comment]
When I did collect errors in the extensions tab of Chrome I got this.  var instaUserInfo=function(){};instaUserInfo.getUserProfile=function(e){"use strict";function t(e){return new Promise(function(t,s){!function(e,t,s){var r=`https://www.instagram.com/web/friendships/${e}/follow/`;$.ajax({url:r,success:function(e){var r=e.match(instaDefOptions.regFindUser);(r||[]).length>0?t(r[1]):s()},error:function(t){console.log(`Error making ajax request to get ${e} profile, status - ${t.status}`),console.log(arguments),s()},async:!0})}(e,t,s)})}function s(e,t,s,r,n){if(function(e){try{JSON.parse(JSON.stringify(e))}catch(e){return!1}return!0}(e.user)){var{id:o,username:i,full_name:u,profile_pic_url_hd:l,biography:c,connected_fb_page:f,external_url:g,followed_by_viewer:_,follows_viewer:w,is_private:d,has_requested_viewer:p,blocked_by_viewer:v,requested_by_viewer:h,has_blocked_viewer:y}=e.user,T=e.user.follows.count,m=e.user.followed_by.count,b=e.user.media.count;_=h?null:_,w=p?null:w;var D={};Object.assign(D,{id:o,username:i,full_name:u,profile_pic_url_hd:l,biography:c,connected_fb_page:f,external_url:g,followed_by_viewer:_,follows_viewer:w,is_private:d,has_requested_viewer:p,blocked_by_viewer:v,requested_by_viewer:h,has_blocked_viewer:y,follows_count:T,followed_by_count:m,media_count:b}),n(D)}else console.log(`returned data in getUserProfile is not JSON - ${a}/${r}`),console.log(arguments),n({full_name:"NA",biography:"The detailed user info was not returned by instagram",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}function r(e,t,s,r){i(e,"red"),instaTimeout.setTimeout(3e3).then(function(){return instaCountdown.doCountdown("status",t,"Getting users profiles",+(new Date).getTime()+instaDefOptions.retryInterval)}).then(()=>{console.log("Continue execution after HTTP error",t,new Date),n(o,s,r)})}function n(e,i,u){var l=`https://www.instagram.com/${e}/?__a=1`;$.ajax({url:l,success:function(e,t,r){s(e,t,r,l,i)},error:function(e){!function(e,s,i){console.log(`Error making ajax request to get ${o} profile, status - ${e.status}`),console.log(arguments),0===e.status?(console.log("Not connected.",new Date),r(instaMessages.getMessage("NOTCONNECTED",+instaDefOptions.retryInterval/6e4),e.status,s,i)):403===e.status?(console.log("HTTP403 error getting the user profile.",new Date),r(instaMessages.getMessage("HTTP403",+instaDefOptions.retryInterval/6e4),e.status,s,i)):429===e.status?(console.log("HTTP429 error getting the user profile.",new Date),r(instaMessages.getMessage("HTTP429",+instaDefOptions.retryInterval/6e4),e.status,s,i)):500===e.status||502===e.status||503===e.status||504===e.status?(console.log("HTTP50X error getting the user profile - "+e.status,new Date),r(instaMessages.getMessage("HTTP50X",e.status,+instaDefOptions.retryInterval/6e4),e.status,s,i)):404===e.status?(console.log("HTTP404 error getting the user profile.",o,new Date),a?t(a).then(function(e){n(e,s,i)}).catch(function(){alert("The error trying to find a new username for - "+a)}):(alert("404 error trying to retrieve user profile, userid is not specified, check if username is correct"),i())):(alert(instaMessages.getMessage("ERRGETTINGUSER",o,e.status)),i())}(e,i,u)},async:!0})}var{username:o,userId:a,updateStatusDiv:i}=e;return new Promise(function(e,t){n(o,e,t)})};

**Comment by thinkpad4** [comment]
That happens when I click your extension icon when in my profile

**Comment by OllegK** [comment]
The extension is trying to guess the username from URL, and according to error message it finds the username as ?hl=en, so probably your url is https://www.instagram.com/<<username>>/?hl=en. I think it is just extension defect, and I will change it to respect URL parameters. I have never seen URL parameters on IG site before, thank you for reporting that. You can try to remove ?hl=en from URL and try again.

**Comment by thinkpad4** [comment]
Thank you SO much!  Works perfect now
