### ISSUE TITLE
"User is Followed by" list download problem

### ISSUE THREAD

**Issue by xxxfinelinexxx** [OllegK/InstagramHelper#15]
I guys,

I'm not able to download my "User is Followed by" list

Every time appears the following error and it cannot finish the fetching procedure:
"Users fetching paused because of HTTP429 error. Continue in 02:51."

We're talking about 2700 followers

My Instagram Helper chrome extension settings are:
(I've increased all the ms intervals but nothing....)

**----------------
Page size for fetching feed AND posts in user profile:
24
Page size for fetching users (insta and common users):
20
Interval between fetching users requests (insta and common), ms:
10000
Interval between the follow requests, ms:
10000
Interval between the liking requests, ms:
10000
----------------------------------**

I hope that you can help me

Regards

**Comment by OllegK** [comment]
Hi,
Even with increased intervals, HTTP429 error appears, and actually the current retry interval 180seconds is not always enough. So when countdown comes to 0, HTTP request is sent to IG and IG again could reply with HTTP429 error. It could happen 2-3 times in a row. However this behavior is handled by extension. Just be patient, and let the extension to complete. Yesterday night I generated a list of 3500 users and HTTP429 appeared several times. I remember myself generating a list of 24k users, and it also worked, but took a long time.
Regards,
Oleg
