### ISSUE TITLE
Today I am getting biography: The detailed user info was not returned by instagram again

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#16]
@OllegK I know that last time I reported getting this message it was because my profile URL had ?hl=en at the end of it, breaking the extension.  After you fixed it I never saw that message again, until today.  My URL doesn't have ?hl=en in it but I'm getting that message every time I click on the extension icon to get the follower list.  It was working this morning at 5am on 3/13/2018 so maybe Instagram changed some code after that.  I have the extension on a secondary account too, also on another browser.  Still happening     https://i.imgur.com/5RT1Z8Q.jpg  This is on Slimjet Version 14.0.16.0 (based on Chromium 57.0.2987.98).

**Comment by OllegK** [comment]
Hello! Yes, Instagram has changed its response for querying the user profile, it worked fine yesterday night for me. Therefore thank you for reporting that, I've just uploaded the new version of extension with quick fix of that (at glance all main functionality works, but I will test it more carefully tonight).

**Comment by thinkpad4** [comment]
Working again for what I use it for, the follower list export.  Thank you very much
