### ISSUE TITLE
Looks like it stopped working, IG changed something

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#17]
@OllegK The program isn't picking up my profile at all now   https://i.imgur.com/sT7JC8w.png

**Comment by OllegK** [comment]
Yes, it happened again, Instagram has changed some security rules, and now the extension cannot get user profile information, I will try to make a fix as soon as possible, but right now I cannot work on it, so please be patient. Thanks.

**Comment by thinkpad4** [comment]
It's working again.  Thank you very much
