### ISSUE TITLE
Getting a Got HTTP500 error all the time now

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#18]
@OllegK Getting a HTTP500 error when trying to fetch the users all the time now, from my 2 different IG accounts

**Comment by thinkpad4** [comment]
Just got this error now too: Uncaught Error: {"message": "execution failure", "errors": [{"message": "Something is wrong. Please check your input and try again.", "locations": []}], "data": {"user": null}, "status": "fail"}

**Comment by OllegK** [comment]
It works for me now. Does it happen immediately when you start fetching or fetching works for some time? Are you fetching your own users or users of another account?

**Comment by thinkpad4** [comment]
When I try to get my own followers, It is now popping up a message Uncaught Error: {"message": "execution failure", "errors": [{"message": "Something is wrong. Please check your input and try again.", "locations": []}], "data": {"user": null}, "status": "fail"}

It doesn't start fetching, I click fetch users then that message pops up

**Comment by OllegK** [comment]
Unfortunately I cannot reproduce this issue, tried on different computers (Windows/Linux), different browsers (Chrome/Chromium), and different instagram accounts (3 accounts). Last summer when it was a huge change in API, seems IG pushed this update incrementally, therefore if so, I could get this issue today or in a couple of days, and other people will also start complain soon. I will keep trying periodically. Just in case to ensure that it is not user-specific issue, could you do:
1) Log out from instagram account
2) Clear browser cache
3) Restart your browser
4) Log in to instagram
5) Navigate to your profile page in instragram, ensure you have URL something like https://www.instagram.com/yourusername/, e.g. if your username is ibm, the url should be exactly as https://www.instagram.com/ibm/ . Nothing else
6) Open the popup window clicking on the extension icon and click the Get Insta Users button.

**Comment by thinkpad4** [comment]
Ok, thank you for trying.  I'll let you know if thing change for me

**Comment by thinkpad4** [comment]
@OllegK OK, tried a different computer, different IP, still getting that same message

**Comment by holymolly** [comment]
`{"message": "execution failure", "errors": [{"message": "Something is wrong. Please check your input and try again.", "locations": []}], "data": {"user": null}, "status": "fail"}`

same here

**Comment by OllegK** [comment]
Good finding, thanks, it seems to me that for some users query_id still works, and for some query_hash should be sent. I will take a closer look a little bit later.

**Comment by OllegK** [comment]
I've just published a new version 0.336, was in rush to fix, but hopefully everything works.

**Comment by thinkpad4** [comment]
I got a bad request when trying to get my own list, HTTP400

**Comment by thinkpad4** [comment]
Failed to load resource: the server responded with a status of 400 () https://www.instagram.com/graphql/query?query_hash=58712303d941c6855d4e888c5f0cd22f&variables=%7B%22id%22:%222883235717%22,%22first%22:%22250%22,%22after%22:null%7D
FetchUsers.js:1 Error: Request failed with status code 400
    at e.exports (chrome-extension://hcdbfckhdcpepllecbkaaojfgipnpbpb/lib/axios.min.js:8:4479)
    at e.exports (chrome-extension://hcdbfckhdcpepllecbkaaojfgipnpbpb/lib/axios.min.js:8:4321)
    at XMLHttpRequest.l.(anonymous function) (chrome-extension://hcdbfckhdcpepllecbkaaojfgipnpbpb/lib/axios.min.js:8:3278)
FetchUsers.js:1 error response data - [object Object]/400
FetchUsers.js:1 Error making http request to fetch the users, status - 400
FetchUsers.js:1 HTTP400 error trying to fetch the users. Thu Apr 19 2018 02:23:21 GMT-0400 (Eastern Daylight Time)
FetchUsers.js:1 Continue execution after HTTP error 400 Thu Apr 19 2018 02:26:24 GMT-0400 (Eastern Daylight Time)
FetchUsers.js:1 Uncaught (in promise) TypeError: Cannot read property 'fetchInstaUsers' of undefined
    at instaTimeout.setTimeout.then.then (FetchUsers.js:1)
instaTimeout.setTimeout.then.then @ FetchUsers.js:1

**Comment by OllegK** [comment]
Thanks, I had another assumption, so very good you put it here. I was able to reproduce the issue setting the amount of fetched users to 250 (as in your request). Please change it to the lower value, 50 works for me. Instagram ignored too high value before, but now it is returning an error.

**Comment by thinkpad4** [comment]
50 works!!!

**Comment by thinkpad4** [comment]
@OllegK Thank you thank you thank you, fetches, exports, WORKS again!!  Thank you very much

**Comment by OllegK** [comment]
On CWS one user reported that even lower value (24 in its case, that was the default value for a long time) of fetching parameters could cause the permanent HTTP400 error you reported above. Therefore I've just published a new version 0.346 that only contains the updated warning on the options dialog, and reduced the default values. In the same time, 50 still works for me at the moment of writing.

**Comment by OllegK** [comment]
Usually, with short liking interval I am facing HTTP403 error, and it disappears after several minutes. What is your liking interval? How long do you have this error? It will last longer, one time I got it, and it was about 2 days. Try to do something different on Instagram to convince IG AI you are not a spammer, e.g. publish a post.

**Comment by lrosenvall** [comment]
Ok, I already had posted this morning, I will wait until Monday to use the extension and see if it resolves the error.
