### ISSUE TITLE
Did you change the way the Excel list looks?

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#19]
@OllegK It used to be User with the profile url, then User ID, then Info

Now it looks like a jumbled mess, ID, then Username with no URL, then FullName, then Profile Pic URL all squished together

The old style was perfect, why did you change it?

**Comment by OllegK** [comment]
Hello, The old export procedure was done using the jqGrid capabilities; therefore only displayed columns in the table were exported to Excel, sometimes I needed to export the column not shown in the table. Maybe in the future versions, I will export to Excel from the pages where jqGrid is not displayed. Also, the old procedure had intermittent errors when export didn't happen, and the user was taken to the error page and generated list was lost. The new approach gives more options about the export procedure and hopefully formatting. In the next several versions the exported procedure will be improved, probably it will be better for you.

**Comment by thinkpad4** [comment]
Cool, looking forward to it

**Comment by OllegK** [comment]
Sorry, it took me a long time to react, I was away for some time. I've just published a version that exports also profile URL.

**Comment by thinkpad4** [comment]
Thank you very much.  The URL helps greatly in keeping track of the people I follow.  While I miss the old style of the Excel list, I can get used to this one

**Comment by OllegK** [comment]
Today I am planning to publish a new version, it contains one urgent bug fix, however in addition to it, there are changes in the exported file: the order of columns is changed, hopefully, it does not create any issues for you, but what could be beneficial - the user_profile is an URL now and clickable (column D)

**Comment by thinkpad4** [comment]
Sweet, looking forward to checking it out.  I'll let you know if I find any bugs

**Comment by thinkpad4** [comment]
@OllegK Did you push 0.345 to Chrome store?  Cause I'm only seeing .344 there

**Comment by OllegK** [comment]
Oh, I thought I did, but it seems I forgot to publish changes. I just did it, it should became available on Chrome Store in about 60 minutes.

**Comment by thinkpad4** [comment]
Got it.  Works good.  I like having the profile urls closer to the left side of the file, so YAY
