### ISSUE TITLE
Querying users that I follow

### ISSUE THREAD

**Issue by joeygallegos** [OllegK/InstagramHelper#21]
Can you tell me what part of the project handles the code that pulls the users I currently follow? I have been working on a Python tool and been searching through the code you have here, and can't seem to figure it out. I really just need the User ID and name.

**Comment by OllegK** [comment]
Hello, please take a look on fetchUsers.js, it sends the requests using axios.get to get the list of followers/following. Max amount of users to be returned is 50, so you need to send several requests with some interval between them.
