### ISSUE TITLE
Request - a complementary unblock feature

### ISSUE THREAD

**Issue by canberrastreets** [OllegK/InstagramHelper#23]
Would it be possible to add a mass unblock feature?  

In essence, if you want an account to not follow you, but you still want them to be able to see your account and posts, it can be most easily achieved by blocking them and then unblocking them.  

Clearly, if there are a significant number of accounts, this would be most easily achieved by a mass block (which already is part of the extension), followed by a mass unblock.

**Comment by OllegK** [comment]
Unblock is available on the same page where the mass block is. Have you tried it? Please take into account that IG has the daily limits for block/unblock.

Just wondering what the reason to want an account do not follow you, but still be able to see your posts. Maybe there is a sense to add a new feature to mass remove your followers?

**Comment by canberrastreets** [comment]
I only saw the block feature?

<img width="700" alt="blocking" src="https://user-images.githubusercontent.com/45731200/49696827-fcbac480-fc03-11e8-8d97-20917379770d.png">

The reason behind wanting to remove accounts from being a follower of your account would generally have to do with engagement.  If you have followers who never like your content or have dropped inactive - it makes your Instagram account look unbalanced (or worse - you have bought followers)  

The received wisdom amongst Instagram gurus is that you want to have a high level of 'engagement' and so followers who are inactive or do not like your content become dead weight.

**Comment by canberrastreets** [comment]
(: No worries and thanks!

**Comment by OllegK** [comment]
Version 0.356 contains mass unblock. 

I've put on my todo list followers remove feature and also block and "first block/second unblock" feature.
