### ISSUE TITLE
Stopped getting "detailed info"

### ISSUE THREAD

**Issue by influencerdeal** [OllegK/InstagramHelper#27]
On a large account with 69000 users it stopped "getting the detailed info" at 7792. Would be great to have some kind of a reload button for these kinds of situations

**Comment by OllegK** [comment]
Not sure what does "stopped getting the detailed info" mean? Could you please describe issue in more details?

**Comment by influencerdeal** [comment]
![Image](https://i.imgur.com/PVeatA1.jpg)

It's stuck here

**Comment by OllegK** [comment]
Please open the developer console and see what is the error message there.

**Comment by OllegK** [comment]
I will create the short instruction how to report the possible bug to help with the reproduction. 

In the meantime please try to repeat the error with the same account.

**Comment by OllegK** [comment]
getUserProfile.js:1 Uncaught (in promise) TypeError: Cannot read property '1' of null
    at a (getUserProfile.js:1)
    at axios.get.then.e (getUserProfile.js:1)
