### ISSUE TITLE
"Error trying to find a new username for -8722807546"

### ISSUE THREAD

**Issue by influencerdeal** [OllegK/InstagramHelper#28]
![Image](https://i.imgur.com/cujzjhx.jpg)

**Comment by OllegK** [comment]
Seems the extension was not able to proceed after that, right?
Did you see any anything in Chrome Dev Console?

**Comment by influencerdeal** [comment]
Yup it got stuck

added it our google doc for bugs as there is a limit here https://docs.google.com/document/d/1YttFl9uRLhL4q3zTMUXM1zxApOiYfaI2u6gC2o1P12k/edit#
