### ISSUE TITLE
Uncaught (in promise) TypeError: s is not a function

### ISSUE THREAD

**Issue by influencerdeal** [OllegK/InstagramHelper#29]
Uncaught (in promise) TypeError: s is not a function
Context
popup.html
Stack Trace
js/ig/getUserProfile.js:1 (anonymous function)

1
const igUserProfileRegularExpression=/window._sharedData = (.*);<\/script>/i,instaUserInfo=function(){};instaUserInfo.getUserProfile=function(e){"use strict";let{username:o,userId:t,updateStatusDiv:s,silient:r,vueStatus:n}=e;return new Promise((e,t)=>{_(o,e,t)});function i(e){return new Promise((o,t)=>{!function(e,o,t){const s=`https://www.instagram.com/web/friendships/${e}/follow/`;axios.get(s,{},{}).then(e=>{const t=e.data.match(instaDefOptions.regFindUser);(t||[]).length>0?o(t[1]):o()},o=>(function(o){console.log(o);const s=o.response?o.response.status:0;s>0&&console.log(`error response data - ${o.response.data}/${s}`),console.log(`Error making http request to get ${e} profile, status - ${s}`),console.log(arguments),t()}))}(e,o,t)})}function a(e,o,s){const r=igUserProfileRegularExpression.exec(e);if(r){const n=JSON.parse(r[1]);if(n.entry_data.ProfilePage&&function(e){try{JSON.parse(JSON.stringify(e))}catch(e){return!1}return!0}(n.entry_data.ProfilePage[0].graphql.user)){let{id:e,username:o,full_name:t,profile_pic_url_hd:r,biography:i,connected_fb_page:a,external_url:l,followed_by_viewer:_,follows_viewer:u,is_private:c,has_requested_viewer:f,blocked_by_viewer:g,requested_by_viewer:d,has_blocked_viewer:w,is_verified:p,is_business_account:m,business_category_name:h,business_email:y,business_phone_number:b}=n.entry_data.ProfilePage[0].graphql.user;const v=n.entry_data.ProfilePage[0].graphql.user.edge_follow.count,P=n.entry_data.ProfilePage[0].graphql.user.edge_followed_by.count,$=n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.count;let D;$>0&&n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges[0]&&(D=new Date(1e3*n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges[0].node.taken_at_timestamp)),_=d?null:_,u=f?null:u;const T={};Object.assign(T,{id:e,username:o,full_name:t,profile_pic_url_hd:r,biography:i,connected_fb_page:a,external_url:l,followed_by_viewer:_,follows_viewer:u,is_private:c,has_requested_viewer:f,blocked_by_viewer:g,requested_by_viewer:d,has_blocked_viewer:w,follows_count:v,followed_by_count:P,media_count:$,latestPostDate:D,is_verified:p,is_business_account:m,business_category_name:h,business_email:y,business_phone_number:b}),s(T)}else console.log(`returned data in getUserProfile is not JSON - ${t}/${o}`),console.log(e),s({username:instaDefOptions.you,full_name:"NA",biography:"The detailed user info was not returned by instagram (no-json)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}else console.log(`exec failed in getUserProfile - ${t}/${o}`),console.log(e),s({username:instaDefOptions.you,full_name:"NA0",biography:"The detailed user info was not returned by instagram (exec)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}function l(e,a,l){console.log(e);const u=e.response?e.response.status:0;if(u>0&&console.log(`error response data - ${e.response.data}/${u}`),console.log(`Error making http request to get user profile ${o}, status - ${u}`),404===u)console.log(">>>HTTP404 error getting the user profile.",o,new Date),t?(console.log(`>>>user id is defined - ${t}`),i(t).then(e=>{console.log(">>>",t,e),e?_(e,a,l):a({username:instaDefOptions.you,full_name:"NA1",biography:"The detailed user info was not returned by instagram (content unavailable)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}).catch(()=>{alert(`The error trying to find a new username for - ${t}`)})):(r||alert("404 error trying to retrieve user profile, userid is not specified, check if username is correct"),l());else if(instaDefOptions.httpErrorMap.hasOwnProperty(u)){console.log(`HTTP${u} error trying to get the user profile.`,new Date),function(e,t,r,i){s(e,"red"),instaTimeout.setTimeout(3e3).then(()=>instaCountdown.doCountdown("status",t,"Getting users profiles",+(new Date).getTime()+instaDefOptions.retryInterval,n)).then(()=>{console.log("Continue execution after HTTP error",t,new Date),_(o,r,i)})}(instaMessages.getMessage(instaDefOptions.httpErrorMap[u],u,+instaDefOptions.retryInterval/6e4),u,a,l)}else alert(instaMessages.getMessage("ERRGETTINGUSER",o,u)),l()}function _(e,o,t){const s=`https://www.instagram.com/${e}/`;axios.get(s,{},{headers:{"x-instagram-ajax":1,eferer:"https://www.instagram.com/"}}).then(e=>{a(e.data,s,o)},e=>l(e,o,t))}};1
const igUserProfileRegularExpression=/window._sharedData = (.*);<\/script>/i,instaUserInfo=function(){};instaUserInfo.getUserProfile=function(e){"use strict";let{username:o,userId:t,updateStatusDiv:s,silient:r,vueStatus:n}=e;return new Promise((e,t)=>{_(o,e,t)});function i(e){return new Promise((o,t)=>{!function(e,o,t){const s=`https://www.instagram.com/web/friendships/${e}/follow/`;axios.get(s,{},{}).then(e=>{const t=e.data.match(instaDefOptions.regFindUser);(t||[]).length>0?o(t[1]):o()},o=>(function(o){console.log(o);const s=o.response?o.response.status:0;s>0&&console.log(`error response data - ${o.response.data}/${s}`),console.log(`Error making http request to get ${e} profile, status - ${s}`),console.log(arguments),t()}))}(e,o,t)})}function a(e,o,s){const r=igUserProfileRegularExpression.exec(e);if(r){const n=JSON.parse(r[1]);if(n.entry_data.ProfilePage&&function(e){try{JSON.parse(JSON.stringify(e))}catch(e){return!1}return!0}(n.entry_data.ProfilePage[0].graphql.user)){let{id:e,username:o,full_name:t,profile_pic_url_hd:r,biography:i,connected_fb_page:a,external_url:l,followed_by_viewer:_,follows_viewer:u,is_private:c,has_requested_viewer:f,blocked_by_viewer:g,requested_by_viewer:d,has_blocked_viewer:w,is_verified:p,is_business_account:m,business_category_name:h,business_email:y,business_phone_number:b}=n.entry_data.ProfilePage[0].graphql.user;const v=n.entry_data.ProfilePage[0].graphql.user.edge_follow.count,P=n.entry_data.ProfilePage[0].graphql.user.edge_followed_by.count,$=n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.count;let D;$>0&&n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges[0]&&(D=new Date(1e3*n.entry_data.ProfilePage[0].graphql.user.edge_owner_to_timeline_media.edges[0].node.taken_at_timestamp)),_=d?null:_,u=f?null:u;const T={};Object.assign(T,{id:e,username:o,full_name:t,profile_pic_url_hd:r,biography:i,connected_fb_page:a,external_url:l,followed_by_viewer:_,follows_viewer:u,is_private:c,has_requested_viewer:f,blocked_by_viewer:g,requested_by_viewer:d,has_blocked_viewer:w,follows_count:v,followed_by_count:P,media_count:$,latestPostDate:D,is_verified:p,is_business_account:m,business_category_name:h,business_email:y,business_phone_number:b}),s(T)}else console.log(`returned data in getUserProfile is not JSON - ${t}/${o}`),console.log(e),s({username:instaDefOptions.you,full_name:"NA",biography:"The detailed user info was not returned by instagram (no-json)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}else console.log(`exec failed in getUserProfile - ${t}/${o}`),console.log(e),s({username:instaDefOptions.you,full_name:"NA0",biography:"The detailed user info was not returned by instagram (exec)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}function l(e,a,l){console.log(e);const u=e.response?e.response.status:0;if(u>0&&console.log(`error response data - ${e.response.data}/${u}`),console.log(`Error making http request to get user profile ${o}, status - ${u}`),404===u)console.log(">>>HTTP404 error getting the user profile.",o,new Date),t?(console.log(`>>>user id is defined - ${t}`),i(t).then(e=>{console.log(">>>",t,e),e?_(e,a,l):a({username:instaDefOptions.you,full_name:"NA1",biography:"The detailed user info was not returned by instagram (content unavailable)",is_private:!0,followed_by_viewer:!1,follows_viewer:!1,follows_count:0,followed_by_count:0,media_count:0})}).catch(()=>{alert(`The error trying to find a new username for - ${t}`)})):(r||alert("404 error trying to retrieve user profile, userid is not specified, check if username is correct"),l());else if(instaDefOptions.httpErrorMap.hasOwnProperty(u)){console.log(`HTTP${u} error trying to get the user profile.`,new Date),function(e,t,r,i){s(e,"red"),instaTimeout.setTimeout(3e3).then(()=>instaCountdown.doCountdown("status",t,"Getting users profiles",+(new Date).getTime()+instaDefOptions.retryInterval,n)).then(()=>{console.log("Continue execution after HTTP error",t,new Date),_(o,r,i)})}(instaMessages.getMessage(instaDefOptions.httpErrorMap[u],u,+instaDefOptions.retryInterval/6e4),u,a,l)}else alert(instaMessages.getMessage("ERRGETTINGUSER",o,u)),l()}function _(e,o,t){const s=`https://www.instagram.com/${e}/`;axios.get(s,{},{headers:{"x-instagram-ajax":1,eferer:"https://www.instagram.com/"}}).then(e=>{a(e.data,s,o)},e=>l(e,o,t))}};

![image](https://user-images.githubusercontent.com/45697689/50564538-e6e18080-0d25-11e9-93c5-24a26337e32d.png)

**Comment by OllegK** [comment]
Please describe the context how did it happen? Your version? Steps to reproduce? Instagram URL?

**Comment by OllegK** [comment]
Not enough context to understand what is the root cause, the best guess is what an network/instagram error happened trying to resolve the username clicking on the popup. The changes will be done to display the alert in this case to make clear what happened.
