### ISSUE TITLE
Not defaulting to xlsx format

### ISSUE THREAD

**Issue by thinkpad4** [OllegK/InstagramHelper#35]
@OllegK With the latest version it defaults to CSV not XLSX like it used to.  Is it possible to make it default to XLSX again?  I like the XLSX format better than the CSV format.  

Thank you very much

**Comment by awelch83** [comment]
...just click the button to export to xlsx. It is not difficult. Don’t be lazy.

Sent from my iPhone

On Jan 31, 2019, at 03:25, Thinkpad4 <notifications@github.com> wrote:

With the latest version it defaults to CSV not XLSX like it used to. Is it possible to make it default to XLSX again? I like the XLSX format better than the CSV format.

Thank you very much

**Comment by thinkpad4** [comment]
@awelch83 It's not lazy it's how the program is meant to work, XLSX (default option) is how it's meant to be.

**Comment by awelch83** [comment]
So now instead of being default, you have to click a button. Cry me a river 😂

Sent from my iPhone

On Jan 31, 2019, at 16:50, Thinkpad4 <notifications@github.com> wrote:

@awelch83 It's not lazy it's how the program is meant to work, XLSX (default option) is how it's meant to be.

**Comment by awelch83** [comment]
It’s “meant to work” however Oleg decides it is supposed to work. This is his project. You’re just using it.

Sent from my iPhone

On Jan 31, 2019, at 16:50, Thinkpad4 <notifications@github.com> wrote:

@awelch83 It's not lazy it's how the program is meant to work, XLSX (default option) is how it's meant to be.

**Comment by OllegK** [comment]
Hello! Export to the CSV works faster and takes less memory, so more records could be exported using the CSV-format. The defaulting to the CSV format was done intentionally.

Maybe I will add remembering the last selected choice (XLSX/CSV) in one of the next versions.
