### ISSUE TITLE
Like a post only when it has likes... 

### ISSUE THREAD

**Issue by HonzaKacer** [OllegK/InstagramHelper#36]
Hi,
I have idea for small extension.

I really appreciate the "bottom limit" of likes for auto-liking posts. But the "up limit" will be useful too.

![056](https://user-images.githubusercontent.com/45458064/52574434-9711d100-2e1c-11e9-9f69-70bc6264d83e.jpg)

Thank you

**Comment by OllegK** [comment]
Hi! It will be implemented in one of the future versions.
