### ISSUE TITLE
ERROR 429 when fetching large number of followers (7000+)

### ISSUE THREAD

**Issue by fsad** [OllegK/InstagramHelper#6]
Hi Olleg,

first let me say that you have written a very great tool for fetching user data from instagram. Congratulations!

Unfortunatelly I get an error when fetching data for a user with more than 6000 followers; Do you have any idea how this could be fixed?

Thanks in advance,
Florian

**Comment by OllegK** [comment]
Hi Florian,

Thank you for feedback and reporting this issue. The extension is getting the list of users from instagram.com server. This error message means that instagram returned HTTP 429 status code (Too Many Requests). To minimize the chance to face such errors, the delay between HTTP requests was intended to be applied (the duration of this delay is configurable on the Options page and default value is 1000ms). However the code had defect, and this delay was not effective, so requests were sent without delay. This defect is fixed now, and also in case of HTTP429, the extension will try to repeat the request after 3 minutes. The new version of extension with included fix is planned to be uploaded on Chrome Web Store this weekeing. 

Best regards,
Oleg

**Comment by OllegK** [comment]
The new version of extension is uploaded to chrome web store. I was able to generate the list with 12k+ users without facing the 429 error

**Comment by fsad** [comment]
Hi Olleg! Great! Thank you very much! It works now!
Best regards,
Florian
