### ISSUE TITLE
Possible export of the generated HTML page?

### ISSUE THREAD

**Issue by MisterAlanBradley** [OllegK/InstagramHelper#8]
First of all... great tool. It really makes some stuff easier. I was now just asking myself if it would be possible to export the generated instaUsers.html including the sort functions?

**Comment by OllegK** [comment]
Thanks. Did I get correctly you want to export the generated list as html-file with sorting capabilities? Chrome "Save As" feature doesn't work for the generated page, and it seems it is not possible to fix. Why do you need such feature? Maybe I could suggest you some other option? If you want to display the generated list on the web page, you could try to use jqGrid (which I use and which is free for not commercial projects) and use the csv-file created from Excel file as datasource for jqGrid.

**Comment by MisterAlanBradley** [comment]
It would be nice to have the list (including the pics) offline to do some researches with it. Thanks for the hint with jsGrid. That would be an option but without the images if I am correct.

**Comment by OllegK** [comment]
jqGrid can display the images when image urls are given. However I think for off-line analysis you would prefer Excel. You can try https://www.extendoffice.com/documents/excel/4212-excel-insert-image-from-url.html for converting URLs to the actual images. I have not tried it, but hopefully it works.
